Social card page
chihacknight/decarbonize-my-state pull request #137
Opened 2022-08-03 23:06 UTC by SuragNuthulapaty

## Overview

Creates the social-card page in order to make the meta images

Adresses #97 

### Demo
Examples of what the social cards look like (note: my screenshots are a bit large, the social cards are the proper size)
![Screen Shot 2022-08-03 at 6 01 18 PM](https://user-images.githubusercontent.com/77648585/182727217-7106eba8-2d52-46b3-b989-a450e393f81f.png)
![Screen Shot 2022-08-03 at 6 01 45 PM](https://user-images.githubusercontent.com/77648585/182727215-c4c0280a-5535-4386-9e57-5282ba13ebac.png)

## Testing Instructions
you can see more states by going to /social-card?state={name of state}

2022-08-03 23:45 UTC, vkoves commented
@SuragNuthulapaty - CI is failing, try running the lint fix in the README like we ran last night. Also just overall amazing work, I'm so impressed that you already got this done!

There's also an issue in the Netlify build with using `document.location` - check state-details, maybe it's just `location` 🤔 

![image](https://user-images.githubusercontent.com/3187531/182731498-3338805c-d99e-4090-b62c-524c535dd38e.png)

2022-08-04 00:57 UTC, SuragNuthulapaty commented
@vkoves I've run the lint and it still seems to not want to work. Also, in state-details we already filter the data for the state so it doesn't use the `document.location` so I'm not sure where to go from there

2022-08-04 01:02 UTC, vkoves commented
@SuragNuthulapaty - it just just be a build issue then. Search for location again though, we extracted the code from state details since it does already have filtered data but it uses the URL to get the state name

2022-08-04 12:19 UTC, SuragNuthulapaty commented
@vkoves state-details doesn't have any use of "URLSearchParams" and its two references to location is from a parameter passed into the function that gives the pathname of the page. We can't use this same approach because the pathname for passing in the location comes to just `/social-card` and doesn't have the `?state=illinois` for example. If there is a way to get the second part of the link, I can't figure it out. 

(Note: just /social-card is from the location parameter, I added the location to denote which console.log I was looking for)
![Screen Shot 2022-08-04 at 7 15 38 AM](https://user-images.githubusercontent.com/77648585/182845046-2bddeb26-82c3-4939-9ff4-6f978beaa619.png)

2022-08-05 01:12 UTC, vkoves commented
It looks like with the actual Gatsby prod build the Illinois icon is always used, and the graph doesn't load, check out this [test url](https://deploy-preview-137--decarb-my-state.netlify.app/social-card/?state=oklahoma):

![image](https://user-images.githubusercontent.com/3187531/182980028-95664de0-cf52-4c5e-a30b-3c7500bc4c75.png)

2022-08-05 03:16 UTC, SuragNuthulapaty commented
Weird, I can't seem to replicate this in the code I have on the branch. Maybe it is a netlify issue?

2022-08-07 18:01 UTC, vkoves commented
@SuragNuthulapaty - it'll probably be easier to walk through this on our call on Tuesday, but a local dev build works differently than the actual prod build. I forget how you run a prod build locally, so I think we'll need Derek's help to debug this.

2022-08-10 02:23 UTC, vkoves commented on src/generate-social-cards.js
> +const placeNames = [
Make sure to split this into a constant. Maybe `src/constants/state-names`?

2022-08-10 02:23 UTC, vkoves commented on src/generate-social-cards.js
> + * @param name {strign} the name of the state to have the social-card taken a picture of
Typo: `strign` - `string`.

2022-08-10 02:24 UTC, vkoves commented on src/generate-social-cards.js
> +}, 3000)
There's an idea in code about avoiding magic strings and magic numbers, which are numbers in code that are uncelar. It's best to move this to a constant, like `const SocialPageDelayMs`. Similarly for the `1000` you can call that something like `WaitDelayMs`.

2022-08-10 02:25 UTC, vkoves commented on src/styles/social-card.css
> +}
Add a newline to end of files - it's kind of an old thing to work with automated file reading systems, but it's a good practice and you can see GitHub flags it up.

2022-08-10 02:28 UTC, vkoves requested changes
Have a few minor starter comments, also noticed the emoji have no spacing with the text:

![Screenshot from 2022-08-09 21-26-12](https://user-images.githubusercontent.com/3187531/183796680-60c8cd5c-9dc6-4d66-88a6-f77a7575abeb.png)

Since space is at a premium, I wonder if we should reduce the font-size of the state icons since states like Connecticut are quite wide, and the visual is more cosmetic than anything.

2022-08-10 02:34 UTC, SuragNuthulapaty commented
@vkoves i already reduce the font size, though I can do it a bit more

2022-08-10 14:57 UTC, vkoves approved these changes
Looks great, awesome work! I skimmed all of the images to make sure no text was broken, and also confirmed all the pages still work properly.

2022-08-10 14:58 UTC, merged