Start FAQ Page, Mostly with EV Questions
chihacknight/decarbonize-my-state pull request #156
Opened 2022-09-07 02:28 UTC by vkoves

## Overview

Adds an FAQ page and links it in the header - this page answers a lot of the common questions I have gotten particularly about electric vehicles, and I plan on adding more info about renewable energy.

Starts on issue #30 but doesn't close it out yet. I'm opening this PR now since there's already a lot of text that might take us some time to discuss, but I think this starter FAQ is better than not having one.

### Demo

Check out the Netlify - this is mostly a giant text page

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

- Load the Netlify and confirm you can go to `/faq` from the header
- Confirm the page is readable on desktop and mobile
- Actually read all the text.

2022-09-13 21:34 UTC, derekeder requested changes
a few small changes to make and we're good to go!

2022-09-13 21:34 UTC, derekeder commented on src/pages/faq.js
> +          <a href="https://carbonswitch.com/do-heat-pumps-work-in-cold-weather/">
additional space needed before this link

2022-09-13 21:34 UTC, derekeder commented on src/pages/faq.js
> +          Google this question or ask a contractor and you might think the
I would axe this first sentence and begin with "Heat pumps absolutely ..."

2022-09-13 21:34 UTC, derekeder commented on src/pages/faq.js
> +          </a>
I think we should also add:

"In colder climates, a potential hurdle to installing heat pumps is home insulation. You may want to get a [blower door test](https://www.energy.gov/energysaver/blower-door-tests) to determine how much heat you are leaking from your home"

2022-09-13 21:34 UTC, derekeder commented on src/pages/faq.js
> +          vehicles has lower fuel costs (electricity per mile is generally
"vehicle"

2022-09-13 21:34 UTC, derekeder commented on src/pages/faq.js
> +          vehicles are much more simpler mechanically speaking and have lower
"much simpler"

2022-09-13 22:32 UTC, vkoves commented
@derekeder - I responded to your feedback but I'm not at home to run the `yarn format` command. Do you mind running that on this branch and pushing it up?

2022-09-14 00:49 UTC, derekeder approved these changes
linter ran & tests pass. merging in!

2022-09-14 00:49 UTC, merged