Fix Mobile Styling
chihacknight/decarbonize-my-state pull request #60
Opened 2022-04-20 04:18 UTC by vkoves

## Overview

Fixes mobile issues on the homepage and state details pages by making sure all graphs scale down to mobile properly and scaling a few large pieces of text.

<details>
  <summary>Comparison</summary>

  | Before | After |
  | --- | --- |
  | ![state-decarbonize netlify app_(iPhone SE) (2)](https://user-images.githubusercontent.com/3187531/164149143-c2b29342-e151-47c7-9093-547f19c4f808.png) | ![localhost_8000_(iPhone SE)](https://user-images.githubusercontent.com/3187531/164149140-70badba2-d78f-457f-8699-b19d272e811c.png) |

</details>

Closes #54.

### Demo

See description.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* Test on mobile, tablet, and desktop
* Also make sure to drag around the width to confirm there's no views at which things look atrocious

2022-04-20 13:53 UTC, derekeder requested changes
Looks great! A few issues with the map, though:

- on mobile view for the [deploy preview](https://deploy-preview-60--state-decarbonize.netlify.app/), clicking on a state takes you to `/undefined`. I didn't see any obvious changes that would impact this functionality
- clicking on small states and DC is pretty much impossible on mobile. do we need to list out each state in a list/table in mobile view?

2022-04-26 01:27 UTC, vkoves commented
@derekeder - I couldn't reproduce the issue you were having with going to `/undefined` on mobile, but I think you are right on needing a table. Mobile users can also zoom in to click their state (which is what I did for DC) but it feels icky to require that.

2022-04-27 02:58 UTC, vkoves commented
As we discussed tonight @derekeder I've added a list of states to improve mobile usability:

![Screenshot from 2022-04-26 21-57-36](https://user-images.githubusercontent.com/3187531/165430682-08f009c9-c3d2-4e5d-85d7-5da2582bf95d.png)

2022-04-27 03:19 UTC, derekeder approved these changes
looks good! one small change and we can merge this in

2022-04-27 03:19 UTC, derekeder commented on src/pages/index.js
> +  console.log('stateSlugs', stateSlugs)
lets axe this print statement

2022-04-27 18:26 UTC, derekeder approved these changes

2022-04-27 18:29 UTC, merged