State target gen progress
chihacknight/decarbonize-my-state pull request #89
Opened 2022-05-17 23:51 UTC by swatland610

This PR should ideally close #28. 

Here's what this PR entails: 
1. Updates to the `state-details.js` page that pulls in data from the graphql queries (similarly to how Dylan set up buildings and vehicles)
2. a new file in `components` called `WindSolarChart.js` that details progress towards our target generation numbers for each state

One language & data choice that I made. I opted to keep the data centered on **installed capacity** rather than **number of solar or wind farms**. I have two reasons for this, I'll summarize them quick...

1. This is how experts talk about this. I couldn't find anyone else who was trying to accurately calculate even a ballpark number for solar panels & wind turbines needed. Plus with assumed improvements to technology over time, it feels like too much of a moving target. 
2. This makes our math SOOOO much easier - and I feel stronger about the results. 

Here's a screenshot of the addition: 
<img width="679" alt="Screen Shot 2022-05-18 at 12 44 58 AM" src="https://user-images.githubusercontent.com/51850964/168930226-c66cb1da-9614-4110-97cb-5a16a04de624.png">

2022-05-17 23:51 UTC, swatland610 commented
@derekeder @nofurtherinformation @vkoves 

this fixes my last PR with all of the merge conflicts - just a heads up!

2022-05-18 01:37 UTC, nofurtherinformation commented on data/raw/state_renewable_gen_targets.csv
> +AL,76967.78,40986.18,14089,68819.6,56621.21,"6,602","132,043",383.58,0,1,0
@swatland610 Alaska is missing here, which is currently causing the build to fail due to missing data

2022-05-18 01:41 UTC, nofurtherinformation commented
Hey @swatland610 - just took a look at the tests are failing due to Alaska and Hawaii missing in the data. 

Plugging in dummy data, it seems to be fine, so the rest of the PR is good to go. I'd suggest putting in a placeholder rows for them and doing a conditional check to see if the data exists to render the new parts of the state details component!

2022-05-18 01:49 UTC, nofurtherinformation requested changes

2022-05-18 01:49 UTC, nofurtherinformation commented on data/raw/state_renewable_gen_targets.csv
> +AZ,64565.23,47611.93,14766.86,65832.16,54764.66,"6,347","126,944",8749.49,644.16,13,1
Adding Hawaii, too, should fix the build issue.

2022-05-24 01:07 UTC, nofurtherinformation commented
Thanks @swatland610 ! I just did a quick lint run to fix the formatting issues our linter picked up, and we should be good to go!

2022-05-24 07:35 UTC, merged